name: Woofy
on: pull_request_review:
    types: [submitted]
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved'
    steps:      
      - uses: HarishTeens/hacktoberfest-greet@v1.1.0
        with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
